quarkus.rest-client.exchange-rate-api.url=https://open.er-api.com

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/projectForm

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true

# Kafka
kafka.bootstrap.servers=localhost:9092

# Producer
mp.messaging.outgoing.order-created.connector=smallrye-kafka
mp.messaging.outgoing.order-created.topic=orders
mp.messaging.outgoing.order-created.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Consumer
mp.messaging.incoming.order-consumer.connector=smallrye-kafka
mp.messaging.incoming.order-consumer.topic=orders
mp.messaging.incoming.order-consumer.group.id=order-service
mp.messaging.incoming.order-consumer.value.deserializer=com.adee.kafka.OrderCreatedEventDeserializer
# OpenSearch
opensearch.url=http://localhost:9200
